[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = true

[rpc_endpoints]
doma_testnet = "https://rpc-testnet.doma.xyz"
mainnet = "${ETH_RPC_URL}"

[etherscan]
doma_testnet = { key = "${ETHERSCAN_API_KEY}", url = "https://explorer-testnet.doma.xyz/api" }

# Doma Testnet Configuration
[profile.doma]
chain_id = 97476
gas_price = 20_000_000_000
eth_rpc_url = "https://rpc-testnet.doma.xyz"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
