[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./" }]
evm_version="cancun"
solc = "0.8.26"
via-ir = true
optimizer = true
optimizer_runs = 200

remappings = [
    "@eigenlayer/=lib/eigenlayer-middleware/lib/eigenlayer-contracts/src/",
    "@eigenlayer-scripts/=lib/eigenlayer-middleware/lib/eigenlayer-contracts/script/",
    "@eigenlayer-middleware/=lib/eigenlayer-middleware/",
    "@openzeppelin/=lib/eigenlayer-middleware/lib/eigenlayer-contracts/lib/openzeppelin-contracts/",
    "@openzeppelin-upgrades/=lib/eigenlayer-middleware/lib/eigenlayer-contracts/lib/openzeppelin-contracts-upgradeable/",
    "forge-std/=lib/forge-std/src/",
    "solidity-bytes-utils/=lib/solidity-bytes-utils/contracts/"
]

[rpc_endpoints]
default_network = "http://127.0.0.1:8545"
localhost = "http://127.0.0.1:8545"

mainnet = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
sepolia = "https://eth-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
arbitrum = "https://arb-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
arbitrumSepolia = "https://arb-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
riseSepolia = "https://testnet.riselabs.xyz"
monadTestnet = "https://testnet-rpc.monad.xyz"
eduChainTestnet = "https://rpc.open-campus-codex.gelato.digital"
pharosDevnet = "https://devnet.dplabs-internal.com"
domaTestnet = "https://rpc-testnet.doma.xyz"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
arbitrum = { key = "${ETHERSCAN_API_KEY}" }
arbitrumSepolia = { key = "${ARBISCAN_API_KEY}" }
riseSepolia = { key = "" }
monadTestnet = { key = "" }
eduChainTestnet = { key = "XXXX" }
pharosDevnet = { key = "" }
domaTestnet = { key = "" }

[fmt]
bracket_spacing = false
int_types = "long"
line_length = 100
multiline_func_header = "params_first"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4

[eduChainTestnet]
name = "blockscout"
url = "https://edu-chain-testnet.blockscout.com/api"